version: "3.7"

services:
    app:
        build: PromTrial
        ports: 
            - "8080:80"
    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - data-prometheus:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    graphana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        volumes:
            - data-graphana:/var/lib/grafana

volumes:
    data-prometheus:
    data-graphana:
